### PR TITLE
Fixes

### PR DESCRIPTION
**Pull request by gaaf**
These are some assorted fixes and enhancements.

### CODE REVIEW

**Comment by LennartHennigs** [comment]
Hey, first of all: thank you! I really appreciate your efforts. Please give me a few days to check out and reply to your pull request.

**Comment by LennartHennigs** [comment]
@gaaf Hey Alex,
one question regarding clarification:
```
if (pos >= upper_bound) {
    if (in_speedup) _setEvent(rotary_event::speedup_ended);
    if (alert) _setEvent(rotary_event::upper_bound_hit);
    steps = upper_bound * steps_per_click;
```

I had the steps adjustment after the calls to make sure that the callback always stay in the bounds.
What was your thought process for moving it to before the call?

**Comment by gaaf** [comment]
Previous, the callback could receive a position out of bounds, as the position was only corrected after the callback. With the change, the callback receives the bound exactly.

**Comment by LennartHennigs** [comment]
@gaaf  FYI: I reverted back the std:function to be able to compile it on AVR.
and I added a few suggestion from GPT4.

And thanks again for your feedback and changes.
highly appreciate this.
will release it in the next days – need to update readme, etc.

**Comment by gaaf** [comment]
>  The only thing I might change from a functionality point of view, is triggering events when you are at the boundaries. I disabled that a while ago. But I could add a book flag to enable/disable this.

IMHO, the left/right/change events should fire unconditionally in case there is an actual change, including _reaching_ the boundaries. If the current position is 1, the lower boundary is 0, and the knob is turned left. Why would one not want to receive the _left_ and _change_ events for changing the position from 1 to 0?

Re-firing while still on the boundary is already protected by a flag.

**Comment by gaaf** [comment]
> @gaaf FYI: I reverted back the std:function to be able to compile it on AVR .

What compiler do you use that doesn't implement 12 year old features?

Can we check for support for the std lib and protect this feature by an #ifdef?

**Comment by LennartHennigs** [comment]
> > @gaaf FYI: I reverted back the std:function to be able to compile it on AVR .
> 
> What compiler do you use that doesn't implement 12 year old features?

Arduino's AVR core (used for boards like Arduino Uno, Mega, and Nano) does not support the std::function template class out of the box because it is part of the C++11 standard library, which is not fully supported by the AVR toolchain. The Arduino AVR core uses the avr-gcc compiler, which has limited C++11 support.

Thus it won’t compile in the Arduino IDE for „their“ boards.

**Comment by LennartHennigs** [comment]
> IMHO, the left/right/change events should fire unconditionally in case there is an actual change, including reaching the boundaries.

Agree to you point. Firing these event is now enabled by default. 
```triggerOnBounds(bool triggerEvents = false)``` allows you to disable them.

**Pull request merged**
