### PR TITLE
Add setPosition function

### PR DESCRIPTION
**Pull request by stephensaid**
Enables user to set a position. Typical use: Mute/Unmute

### CODE REVIEW

**Comment by LennartHennigs** [comment]
Hey, thanks for the suggestion. I will test it on a couple of days and give you feedback.

**Comment by LennartHennigs** [comment]
Hey Stephen,
please take a look at the existing ```resetPosition()``` function. I think it does what you are suggesting.
Cheers
l.

**Comment by stephensaid** [comment]
You're right. I did not notice that I could pass on a value to it.
I assumed it would be reset to 0.
Thanks.

**Comment by LennartHennigs** [comment]
Hey, but you are not the first to miss it. Thus, I'll add a setPosition() function which calls resetReposition()...

**Comment by stephensaid** [comment]
Good idea. Thanks

**Pull request closed without merging**
