### PR TITLE
Add increment option

### PR DESCRIPTION
**Pull request by sblaisot**
This pull requests adds a parameter to ESPRotary() constructor to define increment.
It also adds two new methods `setIncrement(int inc)` to set it afterwards and `getIncrement()` to retrieve current value.

Readme, changelog, keywords and examples have been updated.

### CODE REVIEW

**Comment by LennartHennigs** [comment]
Hey Sébastien,
Thanks for the PR. I am wondering what the need for the increment is. Why do you need it in addition to the steps per click?

Cheers
l.

**Comment by sblaisot** [comment]
Hi Lennart,

increment is different from step-per-click. step-per-click is the number of steps your encoder send when turning 1 click and increment is the increment added to your counter with 1 click. So say my encoder send 4 steps per click (ste-per-click is 4) and I cant to count 10 by 10, I will use and increment of 10.

I hame some use-case un mind :

- Use rotary encoder to tune an FM radio using a module that takes frequency as multiple of 10kHz (i.e. from 8750 for 87.5MHz to 10800 for 108.0 MHz) so I want to count from 8750 to 10800 with an increment of 5

- Having a mode with "rapid" count and another one with "precision count" for rapid selection. like count from 0 to 100, with an increment of 1 in precision mode and an increment of 10 in rapid mode and switching mode with a button (either encoder button or a shift button elsewhere)

I know I can manage this with simple arithmetics in my sketch, by dividing min and max by increment and multiplying balue by increment each time I read it but I find this less readable than having this logic directly in the library.

I cannot use step-per-click for this usage because it is, by design, an integer so its lowest value is 1 so with an encoder sending 4 steps per click, the maximum increment I can get is 4 by setting steps-per-click to 1.
Even worse, with an encoder sending 1 step per click, I have no way to use a larger increment.

**Comment by LennartHennigs** [comment]
Hey,
as soon as I read the first line of your answer, I knew what you were going to say - and you are, of course right. (Insert a facepalm here)  
Give me a few days to test it and merge it.
Thank you again!

Have a good weekend. 
l.

**Comment by sblaisot** [comment]
Hi @LennartHennigs 

Any news?

**Comment by LennartHennigs** [comment]
Sorry, it took a while. Life happened!
Thanks again for the PR and the changes.
Cheers
l.

**Pull request merged**
